# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            WMT24 Chat Task
#tagline:          'A Jekyll theme'
description:      'This shared task will examine machine translation in the Chat domain.'
#url:              http://hyde.getpoole.com
baseurl:          /

#author:
#  name:           'Mark Otto'
#  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2024

github:
  repo:           https://github.com/WMT-Chat-task/chat-task-2024-data
